<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Terminex.Security.Srp</PackageId>
    <Version>0.1.0-beta.1</Version>
    <Description>Implementation of the Secure Remote Password Protocol (SRP-6a), both for the client and the server. Provides password-based authentication without transmitting passwords over the network. Includes client-side session management and secure credential verification.</Description>
    <PackageTags>security;srp;srp-6a;authentication;password-auth;client;zero-knowledge;proof;secure-login</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Terminex.Security.Abstraction\Terminex.Security.Abstraction.csproj" />
    <ProjectReference Include="..\Terminex.Security.Configuration\Terminex.Security.Configuration.csproj" />
    <ProjectReference Include="..\Terminex.Security.Utilities\Terminex.Security.Utilities.csproj" />
  </ItemGroup>

</Project>
